# Kubernetes deployment definition 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit
        image: adilsonsilvajr/streamlit-app:latest
        resources:
          limits:
            cpu: "2"
            memory: "512Mi"
        env:
        - name: STREAMLIT_APP
        ports:
        - containerPort: 8501
