// Jenkins pipeline configuration 
pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/adilsonsilvajr/piproject-k8s.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t adilsonsilvajr/streamlit-app ./ci_cd/docker-app'
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'docker push adilsonsilvajr/streamlit-app'
            }
        }
        stage('Deploy with Ansible') {
            steps {
                sh 'ansible-playbook ci_cd/ansible/deploy.yml'
            }
        }
    }
}
