// Jenkins pipeline configuration 
pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/your_username/your_streamlit_repo.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t your_dockerhub_username/streamlit-app ./ci_cd/docker-app'
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'docker push your_dockerhub_username/streamlit-app'
            }
        }
        stage('Deploy with Ansible') {
            steps {
                sh 'ansible-playbook ci_cd/ansible/deploy.yml'
            }
        }
    }
}
